const actionsTypes = {
    LOGIN:"LOGIN",
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    FETCH_SUCCESS: "FETCH_SUCCESS",
    FETCH_DATA_FAIL: "FETCH_DATA_FAIL",
    CREATE_USER:"CREATE_USER",
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAIL: 'CREATE_USER_FAIL',
    ISLOADING: 'ISLOADING',
    ISSIGNUP: 'ISSIGNUP',
    CLEAR: 'CLEAR',
    SELECTED_PROFILE:"SELECTED_PROFILE",
    SIGN_OUT:"SIGN_OUT",
    FETCH_ALL_USERS:"FETCH_ALL_USERS",
    ADMIN_LOGIN:"ADMIN_LOGIN",
    SET_BLOCK:"SET_BLOCK",
    APPLIED_COMPANY:"APPLIED_COMPANY",
    APPLICANTS_COMPANY:"APPLICANTS_COMPANY",
    SELECTED_JOB:'SELECTED_JOB'
}

export default actionsTypes;